---
:pid_file: tmp/orator.pid
:log_file: log/orator.log
:server_options:
  :host: 0.0.0.0
  :port: 8080
:orators:
  - app/orators/application_orator.rb
  - app/orators/*
:require:
  - config/orator/router.rb
